### ISSUE TITLE
Unfair comparison with JHipster Spring version

### ISSUE THREAD

**Issue by derkoe** [micronaut-projects/micronaut-comparisons#1]
First of all thanks for Micronaut and the benchmarks!

I tested the benchmarks locally and found some problems:
* the Spring version has DEBUG logging activated, Micronaut versions log nothing
* the Spring version writes audit logs, Micronaut versions do not have auditing included

I have removed the Spring logging and audit logs and this are my results (used Device: ZBook Studio G3 / i7-6700HQ / 32GB / Fedora Linux 32):

|                                            | Spring Boot 2.2 | Micronaut 1.3.4 | Micronaut 2.0.0 M2 |
|:-------------------------------------------|----------------:|----------------:|-------------------:|
| Simple: Start Up (Best of 5)               | 2825 ms         | 1041 ms         | 817 ms             |
| Simple: Time to First Response (Best of 5) | 3027 ms         | 1797 ms         | 1499 ms            |
| JHipster: Number of Requests (60s)         | 109,075         | 122,896         | 139,183            |
| JHipster: Mean Response Time               | 454 ms          | 404 ms          | 349                |
| JHipster: Mean Requests Per Second         | 1983.182        | 2234.473        | 2485.411           |
| Memory Consumption After Load Test         | 478.980 MB      | 509.562 MB      | 517.753 MB         |

**Comment by JasonTypesCodes** [comment]
Thanks for the feedback @derkoe.  I'll make those updates and check my results.

**Comment by JasonTypesCodes** [comment]
Thanks again for your suggestion @derkoe.  I've made those updates, and as you stated, it improved the performance of the SB JHipster app considerably!  

My before and after can be seen in this [diff](https://github.com/micronaut-projects/micronaut-comparisons/commit/430485cc77a5347f82d3a69db5eb22f31831d6ce). 

The thing I haven't been able to reproduce, is your memory consumption results.  I've not yet witnessed the Micronaut JHipster app using more memory after load than the SB one.  I'm interested in any thoughts you have on why we might be getting different results there.

I'll be putting out an update to our blog post tomorrow and I'll give you a proper hat tip there.  Thanks again!

**Comment by derkoe** [comment]
Thanks for the update!! I'm not sure why we see different results in memory but this could be caused when exactly the last GC was triggered and probably the exact JVM version.

I have used this OpenJDK 11 provided by Fedora:
```
$ java -version 
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment 18.9 (build 11.0.6+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.6+10, mixed mode, sharing)
```
